name: Deploy to Layer0

on:
  workflow_dispatch:
  push:

jobs:
  deploy-to-layer0:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn --prefer-offline
      - run: npm run layer0:deploy -- --token=$LAYER0_DEPLOY_TOKEN
        env:
          LAYER0_DEPLOY_TOKEN: ${{ secrets.LAYER0_DEPLOY_TOKEN }}
      - run: npm run layer0:deploy -- --skip-build --site=nuxt-isr --token=$LAYER0_DEPLOY_TOKEN_1
        env:
          LAYER0_DEPLOY_TOKEN_1: ${{secrets.LAYER0_DEPLOY_TOKEN_1}}
